# Generated by Django 3.2.7 on 2023-02-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloficial',
            name='rol',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Root'), (1, 'Oficial')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='oficial',
            name='rol',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Root'), (1, 'Oficial')], default=0, null=True),
        ),
    ]
