# Generated by Django 3.2.7 on 2023-02-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230216_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloficial',
            name='username',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='oficial',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
